var GAME_LEVELS = [
  ["                                           x                                    ",
   "                                           x                                    ",
   "                                           x                                    ",
   "                                o o        x                                    ",
   "                               xxxxx       x                                    ",
   "                           o       x       x                         xxxxxxxxx  ",
   "   *           o     o     xx      x    xxxx  xxx        xxx                 x  ",
   "   xxxx       xxx   xxx            x    x     xvx        xvx                 x  ",
   "              x!!!!!!!x            x   !x                                    x  ",
   "              xxxxxxxxx xx  o      x    x                                    x  ",
   "                           xxx    xx    x                                    x  ",
   "                                   x    x                                    x  ",
   "xxxx                               x    x                                    x  ",
   "  x              o o               x    x                                 o  x  ",
   "  x             xxxx              xx!   x                           o     xxxx  ",
   "  x            x!!!!               x                  o          xxxxx       x  ",
   "  x  @         x!!!! o             x  o         x  x  x  x  x  xxx!!!!!!!!!!!x  ",
   "  xxxxxxxx#xxxxxxxxxxxx   xxx#xxxxxxxxxxxxxxxx!!x!!x!!x!!x!!x!!x xxxxxxxxxxxxx  ",
   "                      x!!!x                                                     ",
   "                      xxxxx                                                     ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxvxxxxxxvxxxxxxvxxxxxvxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "x                                           x!!!!!!!!!!!!!!!!!!!!!!xvx!!!xvx!!xvx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "x@                                          x!!!!!!!!!!!!!!!!!!!!!!x x!!!x x!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxx                                         x!!!!!!!!!!!!!!!!!!!!!!x x!!!x x!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "x    o             o            o           x!!!!!!!!!!!!!!!!!!!!!!x x!!!x x!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxx xxxxxx #xxxxx xxxxx xxxxx         xxxxxxxxxxxxxxxxxxxxxxxx xxxxx xxxx xxxxxxxxxxxvvvvvvvvvvvvvvvvvvvvvvv",
   "!!!!!!!!x!x!!!!x!x!!!!x!x!!!x!x!!!x!        x!!!!!!!!!!x                                                          ",
   "!!!!!!!!xxx!!!!xxx!!!!xxx!!!xxx!!!x        !x!!!!!!!!!!x                                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    o    x!!!!!!!!!!x                                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x!!!!!!!!!!x            xxxxxxxxxxxxx#xxx                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!       x!!!!!!!!!!=            x               x                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x!!!!!!!!!!x         xxxx               x      #######################",
   "!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx=        x!!!!!!!!!!xx                           x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x                          x!!!!!!!!!!xxx o                        x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x             o            x!!!!!!!!!!xxxxxxx  o                   x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x                          x!!!!!!!!!!x        xx   xxx            x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x      xxxxxxxxxxxxxxxxx!!!x!!!!!!!!!!x                  xxx       x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x=     x!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!x                          xxx!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x*    =x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!=                            x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x      xxxxxx xxxx|xxxxxxxxxxxxxxxxxxxx                          o x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x                 *         x=   o    x                            x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x                                                                xxx!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x                                                                  x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!x o      o                                                 o       x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!xxxxxxx xxx x xxxxxx#x|xxxxxxxxxx#xxxxxxxxxxxx       o    xxx    o x!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!x!x x!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx    xxx   x x   xxxx!!!   !!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!x!x x!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x x!!!x x!!!x xx!!x   x!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!x!x x!x|x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x x!!!x x!!!x xx!xx   xx!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!x!x x!x!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x x!!!x x!!!x xxx  oo   x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!x!x x!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx xxxxx xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                        vv                                                  vv                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                       xxxxx                                               xxxxx                              ",
   "                       x   x  xxxx              ooooo                xxxx  x   x                              ",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxx                              ",
   "                       x                x!!x                                   x                              ",
   "                       x                xvvx              xxxxx                x                              ",
   "                       x                                      xxx              x                              ",
   "                       xxx==                                       xxxxx    o  x                              ",
   "                       xvx                                                     x                              ",
   "                       x                                                 xxxxx#x                              ",
   "                       x                                          xxxxxxxx     x                              ",
   "                       x                                        xxx            x                              ",
   "                       x                                      xxx              x                              ",
   "                       x                xxxx                xxx                x                              ",
   "                       x         xxxx        xxxxxx   xxx                      x                              ",
   "                       x                              xvx                      x                              ",
   "                       x  xxxx    o                                            x                              ",
   "                       x     xxxx                                              x                              ",
   "                       x        xxxx                                           x                              ",
   "                       x*          xxxx=               o         xxxxx       xxx                              ",
   "                       xxx =              xxxxxx     xxxxx                     x                              ",
   "                       x                                                    o  x                              ",
   "                       x                                                       x                              ",
   "                       xo                                               xxxxxxxx                              ",
   "                       x      xxxx                               xxxx          x                              ",
   "                       x              xxxx=       o       =xxx                 x                              ",
   "xxxxxx                 xx                xxx#xxxxxxxxxxxxxxx                   x                              ",
   "x                      x                                                       x                              ",
   "x                      xo                                                     xx                              ",
   "x                      x                                                      |x                              ",
   "x                      xxxxxx                                                  x                              ",
   "x                      x         xxxxxx    xxx=    o     xxx    xxxx#xxxx      x                              ",
   "x                      x                     xxxxxxxxxx#xx              xx     x                              ",
   "x                                                                             ox                              ",
   "x                                                                          xxxxx                              ",
   "x                                                                       xxxx   x                              ",
   "x @                                                                            x                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             x x   xx   x x     x   x   xx   x  x   x   vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
   "             x x  x  x  x x     x x x  x  x  xx x   x                                                         ",
   "              x   x  x  x x     x x x  x  x  x xx                                                             ",
   "              x    xx    x       x x    xx   x  x   x                                                         ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  @                                                                                                          o",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
